failure:
- type: network-packageLoss
  startAfter: 20
  duration: 60
  level: 1
  nodeName: node0
  label: network failure test
- type: nodeFailure
  startAfter: 10
  duration: 20
  level: 1
  nodeName: node1
  label: node failure test